server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # Cache para assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA: todas as rotas servem index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Saúde do container
    location /health {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
